import fs from 'fs/promises';import path from 'path';import {fileURLToPath} from 'url';import {WATER_REMINDER_INTERVALS} from '../models/User.js';import {nextWaterReminderAt} from '../services/notificationScheduler.js';
const uploadsDirectory=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../uploads');
export function getProfile(req,res){res.json(req.user)}
export async function updateProfile(req,res,next){try{const allowed=['name','phone','age','gender','bloodGroup','height','weight','emergencyContact','address','dateOfBirth','medicalConditions'];allowed.forEach(key=>{if(req.body[key]!==undefined)req.user[key]=req.body[key]});await req.user.save();res.json(req.user)}catch(e){next(e)}}
// Only ever deletes files inside backend/uploads, whatever the stored path says.
async function deleteStoredPhoto(storedPath){if(!storedPath)return;const target=path.resolve(uploadsDirectory,path.basename(storedPath));if(target.startsWith(`${uploadsDirectory}${path.sep}`))await fs.unlink(target).catch(()=>{})}
export async function uploadProfilePicture(req,res,next){try{if(!req.file)return res.status(400).json({message:'Please select a JPG, PNG or WEBP image'});const previous=req.user.profilePicture;req.user.profilePicture=`/uploads/${req.file.filename}`;try{await req.user.save()}catch(e){await fs.unlink(req.file.path).catch(()=>{});throw e}await deleteStoredPhoto(previous);res.json(req.user)}catch(e){next(e)}}
export async function removeProfilePicture(req,res,next){try{const previous=req.user.profilePicture;req.user.profilePicture=undefined;await req.user.save();await deleteStoredPhoto(previous);res.json(req.user)}catch(e){next(e)}}
export async function updateSettings(req,res,next){try{const input=req.body||{};const current=req.user.settings?.toObject?.()||{};const currentWater={enabled:Boolean(current.waterReminders?.enabled),intervalMinutes:current.waterReminders?.intervalMinutes||120};const next={healthNotifications:current.healthNotifications,waterReminders:{...currentWater},language:current.language,darkMode:current.darkMode};for(const key of ['healthNotifications','darkMode']){if(input[key]!==undefined){if(typeof input[key]!=='boolean')return res.status(400).json({message:`${key} must be true or false`});next[key]=input[key]}}if(input.language!==undefined){if(!['en','te'].includes(input.language))return res.status(400).json({message:'Unsupported language'});next.language=input.language}
const water=input.waterReminders;if(water!==undefined){if(!water||typeof water!=='object')return res.status(400).json({message:'waterReminders must be an object'});if(water.enabled!==undefined){if(typeof water.enabled!=='boolean')return res.status(400).json({message:'waterReminders.enabled must be true or false'});next.waterReminders.enabled=water.enabled}if(water.intervalMinutes!==undefined){if(!WATER_REMINDER_INTERVALS.includes(water.intervalMinutes))return res.status(400).json({message:'Unsupported reminder interval'});next.waterReminders.intervalMinutes=water.intervalMinutes}}
req.user.settings=next;
// Turning reminders on (or changing the interval) starts a fresh countdown; turning them off cancels the next one.
if(!next.waterReminders.enabled)req.user.waterReminderNextAt=undefined;else if(!currentWater.enabled||currentWater.intervalMinutes!==next.waterReminders.intervalMinutes)req.user.waterReminderNextAt=nextWaterReminderAt(next.waterReminders.intervalMinutes);
await req.user.save();const saved=req.user.toObject();delete saved.waterReminderNextAt;res.json(saved)}catch(e){next(e)}}
