import {useEffect,useState} from 'react';import {FiBell,FiDroplet,FiGlobe,FiMoon,FiSend} from 'react-icons/fi';import {useAuth} from '../../auth/AuthContext';import {updateSettings} from '../../services/auth';import {sendTestNotification} from '../../services/notifications';import {getApiErrorMessage} from '../../services/api';import {ensurePushSubscription,notificationPermission,requestNotificationPermission} from '../../utils/notifications';import {languages} from '../../utils/speech';import '../../styles/settings.css';
const INTERVALS=[[30,'30 minutes'],[60,'1 hour'],[120,'2 hours'],[180,'3 hours'],[240,'4 hours']];
const BLOCKED='Browser notifications are blocked. Please allow notifications for HealthNova in your browser settings.';
const formFrom=settings=>({healthNotifications:Boolean(settings.healthNotifications),waterReminders:{enabled:Boolean(settings.waterReminders?.enabled),intervalMinutes:settings.waterReminders?.intervalMinutes||120},language:settings.language,darkMode:Boolean(settings.darkMode)});
// Keeps the permission state in sync if the user changes it from the browser's site settings.
function usePermission(){const [permission,setPermission]=useState(notificationPermission);useEffect(()=>{let status;let active=true;const refresh=()=>active&&setPermission(notificationPermission());navigator.permissions?.query({name:'notifications'}).then(result=>{status=result;result.onchange=refresh}).catch(()=>{});window.addEventListener('focus',refresh);return ()=>{active=false;if(status)status.onchange=null;window.removeEventListener('focus',refresh)}},[]);return [permission,setPermission]}
export default function Settings(){const {settings,updateUser}=useAuth();const [form,setForm]=useState(()=>formFrom(settings));const [status,setStatus]=useState({type:'',text:''});const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);const [enabling,setEnabling]=useState('');const [testing,setTesting]=useState(false);const [permission,setPermission]=usePermission();
const change=patch=>{setForm(current=>({...current,...patch}));setStatus({type:'',text:''})};
// Turning a notification switch on asks for permission (from this click), then registers this browser for push.
// The switch only stays on when both succeed, so it reflects what will really happen.
const enableNotifications=async key=>{setNotice('');setEnabling(key);try{const result=await requestNotificationPermission();setPermission(result);if(result==='denied'){setNotice(BLOCKED);return false}if(result==='unsupported'){setNotice('This browser does not support notifications. Try Chrome, Edge or Firefox over HTTPS.');return false}if(result!=='granted'){setNotice('Notifications stay off until you allow them in the browser prompt.');return false}await ensurePushSubscription();return true}catch(error){setNotice(error.reason?error.message:getApiErrorMessage(error,'Notifications could not be turned on. Please try again.'));return false}finally{setEnabling('')}};
const toggleHealth=async checked=>{if(!checked)return change({healthNotifications:false});if(await enableNotifications('health'))change({healthNotifications:true})};
const toggleWater=async checked=>{if(!checked)return change({waterReminders:{...form.waterReminders,enabled:false}});if(await enableNotifications('water'))setForm(current=>({...current,waterReminders:{...current.waterReminders,enabled:true}}))};
const granted=permission==='granted';const healthOn=form.healthNotifications&&granted;const waterOn=form.waterReminders.enabled&&granted;
const saved=formFrom(settings);const dirty=JSON.stringify(form)!==JSON.stringify(saved);
const save=async()=>{if(saving)return;try{setSaving(true);const response=await updateSettings(form);updateUser(response.data);const water=form.waterReminders;const restarted=water.enabled&&(!saved.waterReminders.enabled||saved.waterReminders.intervalMinutes!==water.intervalMinutes);setStatus({type:'success',text:restarted?`Settings saved. Your next water reminder is due in about ${INTERVALS.find(([value])=>value===water.intervalMinutes)?.[1]}.`:'Settings saved.'})}catch(error){setStatus({type:'error',text:getApiErrorMessage(error,'Could not save settings. Please try again.')})}finally{setSaving(false)}};
const test=async()=>{if(testing)return;try{setTesting(true);setNotice('');await ensurePushSubscription();await sendTestNotification(waterOn&&!healthOn?'water':'test');setStatus({type:'success',text:'Test notification sent. It should appear in a few seconds.'})}catch(error){setStatus({type:'error',text:error.reason?error.message:getApiErrorMessage(error,'The test notification could not be sent.')})}finally{setTesting(false)}};
const blockedNote=permission==='denied'&&(form.healthNotifications||form.waterReminders.enabled)?BLOCKED:'';
return <><header className="page-header"><div><span>PREFERENCES</span><h1>Settings</h1><p>Manage your Health-Nova-AI experience.</p></div></header><section className="settings-card">
<label><FiBell/><div><b>Health notifications</b><small>Get notifications when HealthNova has something important to tell you, like a finished report analysis.</small></div><input className="switch" type="checkbox" role="switch" aria-busy={enabling==='health'} disabled={Boolean(enabling)||permission==='unsupported'} checked={healthOn} onChange={event=>toggleHealth(event.target.checked)}/></label>
<div className="settings-group"><label><FiDroplet/><div><b>Drink water reminders</b><small>Get gentle reminders to stay hydrated.</small></div><input className="switch" type="checkbox" role="switch" aria-busy={enabling==='water'} disabled={Boolean(enabling)||permission==='unsupported'} checked={waterOn} onChange={event=>toggleWater(event.target.checked)}/></label>
{waterOn&&<label className="settings-sub"><span>Reminder interval</span><select value={form.waterReminders.intervalMinutes} onChange={event=>change({waterReminders:{...form.waterReminders,intervalMinutes:Number(event.target.value)}})}>{INTERVALS.map(([value,label])=><option key={value} value={value}>Every {label}</option>)}</select></label>}</div>
{(notice||blockedNote)&&<p className="settings-note settings-banner" role="alert">{notice||blockedNote}</p>}
{(healthOn||waterOn)&&<div className="settings-test"><small>Delivered as browser push notifications. Keep notifications for your browser allowed in your device settings.</small><button type="button" className="link-btn" onClick={test} disabled={testing}><FiSend/>{testing?'Sending…':'Send test notification'}</button></div>}
<label><FiGlobe/><div><b>Preferred language</b><small>Used by the Nova assistant for replies and voice.</small></div><select value={form.language} onChange={event=>change({language:event.target.value})}>{Object.entries(languages).map(([code,{label}])=><option key={code} value={code}>{code==='en'?'English':`Telugu (${label})`}</option>)}</select></label>
<label><FiMoon/><div><b>Dark mode</b><small>Use a calm night-sky appearance across HealthNova.</small></div><input className="switch" type="checkbox" role="switch" checked={form.darkMode} onChange={event=>change({darkMode:event.target.checked})}/></label>
{status.text&&<p className={`status-text ${status.type==='error'?'error-text':''}`} role="status">{status.text}</p>}<button className="primary-btn settings-save" onClick={save} disabled={saving||!dirty}>{saving?'Saving...':'Save Settings'}</button></section></>}
